server/src/routes/cvmaker.py
from flask import Blueprint, render_template , current_app
from helpers.responses import get_response
from flask_wtf.csrf import generate_csrf
from helpers.auth import handle_noneed_logged_user, is_user_logged
cvmaker_bp = Blueprint("cvmaker",__name__)

@cvmaker_bp.route("/cvmaker")
def cvmakerpage():
    if is_user_logged() == True:
        current_app.isLogged = True
    return handle_noneed_logged_user("cvmaker.html",pagetitle="(Cv Maker))✌Dr.Null",isLogged=current_app.isLogged , csrf_token=generate_csrf())

server/src/routes/notes.py
from flask import Blueprint, current_app ,jsonify, make_response, request, redirect, url_for, render_template
from helpers.auth import admin_required, handle_unauthenticated_user, is_user_logged
from helpers.responses import  get_response
from flask_wtf.csrf import generate_csrf


notes_bp = Blueprint("notes",__name__)
@notes_bp.route("/notes")
def notespage():
    firebase_services = current_app.firebase_services
    database = firebase_services['database']         # 
    if is_user_logged() == True:
        isLogged = True
        uid = request.cookies.get('__session') 
        try:

            signedUser =  database.child("users").child(uid).get().val()
            template =   render_template("notes.html",pagetitle="(Notes))✌Dr.Null",username=signedUser['username'],isLogged=isLogged ,csrf_token=generate_csrf()) 
            return get_response(template)
        except:
            response = make_response()
            response= jsonify({"error":"somthing error"})  
            return response
    else:
       return  handle_unauthenticated_user()

server/src/routes/search.py
from flask import Blueprint, current_app ,jsonify, make_response, request, redirect, url_for, render_template
import requests
from helpers.responses import get_response
from helpers.auth import handle_noneed_logged_user, is_user_logged
from flask_wtf.csrf import generate_csrf

search_bp = Blueprint("search",__name__)

@search_bp.route("/search")
def searchpage():
    if is_user_logged() == True:
        current_app.isLogged= True
    return handle_noneed_logged_user("search.html", pagetitle="(search)✌Dr.Null" ,isLogged=current_app.isLogged , csrf_token=generate_csrf())


@search_bp.route("/searchItem", methods=['POST']) 
def searchItem():
        try:

            keyword = request.form.get('keyword')
            cookie = request.form.get('cookie')
            url = "https://dawaok.al-dawaa.com/instore/jquery-functions/ajax-customer-sku-search.php"

            payload = f'keyword={keyword}'
            headers = {
            'Cookie': f'{cookie}',
            'Content-Type': 'application/x-www-form-urlencoded'
            }   
            response = requests.request("POST", url, headers=headers, data=payload)
            code = response.status_code
            if(code == 404):
                response= jsonify({"error":"ok"}) 
            else:
                
                response= jsonify({"success":"ok","result": response.text})  

        except :
            response= jsonify({"error":"ok"})  
        return response


# @search_bp.route("/testSession", methods=['POST']) 
# def testsession():
#         try:

#             keyword = request.form.get('test')
#             cookie = request.form.get('cookie')
#             url = "https://dawaok.al-dawaa.com/instore/jquery-functions/ajax-customer-sku-search.php"

#             payload = f'keyword={keyword}'
#             headers = {
#             'Cookie': f'{cookie}',
#             'Content-Type': 'application/x-www-form-urlencoded'
#             }   
#             response = requests.request("POST", url, headers=headers, data=payload)
#             code = response.status_code
#             if(code == 404):
#                 response= jsonify({"error":"ok" ,"result":code}) 
#             else:
                
#                 response= jsonify({"success":"ok","result":code})  

#         except :
#             response= jsonify({"error":"ok"})  
#         return response

server/src/routes/upload.py
from flask import Blueprint, current_app, make_response, request, render_template
from helpers.auth import handle_unauthenticated_user, is_user_logged, handle_logged_in_user, handle_token_authentication
from helpers.responses import get_response

upload_bp = Blueprint('upload', __name__)

@upload_bp.route("/upload", methods=['GET'])
def upload_page():
    """Handle the upload page route."""
    firebase_services = current_app.firebase_services
    database = firebase_services['database']  # Pyrebase DB
    admin_auth = firebase_services['admin_auth']  # Firebase Admin Auth

    # Check if the user is already logged in
    if is_user_logged():
        return handle_logged_in_user(
            database,
            "upload.html",
            "(Upload)✌Dr.Null"
        )

    # If the user is not logged in, check for a token
    token = request.args.get('token')
    if token is None:
        return handle_unauthenticated_user()

    # If the user has a token, verify it
    return handle_token_authentication(
        token,
        database,
        admin_auth,
        "upload.html",
        "(Upload)✌Dr.Null"
    )

server/src/templates/layouts/chatbot.html
<div class="contact-loader">
  <div class="loader"></div>
  <span class="loader-span">sending ...</span>
</div>
<div id="chat-circle" class="toggle-chatbox-btn">
   Feedback
  </div>

  <div class="chat-box">
    <div class="chat-box-header">
      <div>
        <i class="fa-regular fa-envelope"></i>
        <span>Leave (A)Message</span>
      </div>
      <div>
        <span class="close-chatbox"><i class="fa-solid fa-xmark"></i></span>
      </div>
    </div>
    <form class="form_msg" method="POST" action="">
      <div class="form-group">
        <input type="text" name="contact-name" class="form-control contact-name"  placeholder="your name" required>
      
      </div>
      <div class="form-group">
        <input type="email" name="contact-email" class="form-control contact-email"  placeholder="your email" required>
      
      </div>
      <div class="form-group">
        <input type="text" name="contact-phone" class="form-control contact-phone"  placeholder="your phone ((optional))">
      </div>
      <div class="form-group">
        <textarea class="form-control contact-msg"  name="contact-msg" rows="3" placeholder="write your message here .." required></textarea>
    
      </div>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit"  class="btn btn-primary send_msg">send <i class="fa-solid fa-paper-plane"></i>
          </button>
        </div>
      </div>
    </form>
    <div class="chat-box-overlay"></div>
  
  </div>
  

server/src/templates/layouts/contact.html
    <!-- start of contact page  -->
    <div class="contact" id="contact">
      <div class="contact-wraper">
        <div class="upper">
          <h2 class="caption-5 text-center">Get in Touch</h2>
          <h2 class="heading-2 text-center heading-card">Contact Me</h2>
          <div class="email-wraper">
            <a href="mailto:hasanmeady781@gmail.com" class="email-link"><i class="fa-solid fa-envelope email-icon"
                aria-label="email"></i>hasanmeady781@gmail.com</a>
            <a href="https://wa.me/+966546035917" class="email-link" aria-label="phone"><i
                class="fa-solid fa-phone"></i>+966-546035917</a>
            <a href="https://www.facebook.com/hasan.meady.5/" class="face-link" target="_blank" aria-label="facebook"><i
                class="fa-brands fa-facebook facebook-icon"></i>Facebook</a>
            <a href="https://www.linkedin.com/in/hasan-meady-7679081b4/" class="face-link" target="_blank"
              aria-label="linkedin"><i class="fa-brands fa-linkedin"></i>Linkedin</a>
            <a href="https://hasanmeady.web.app" class="face-link" target="_blank"
              aria-label="Portfolio"><i class="fa-solid fa-user-tie"></i>My Portfolio</a>
          </div>
        </div>
        <div class="footer" id="footer">
          <a href="{{ url_for('privacy.privacypage') }}" class="privacy-link"> Privacy Policy</a>
          <p class="copyright caption-3">Made with <span class="love-icon"><i class="fa-regular fa-heart"></i></span>By
            Hasan Meady</p>
        </div>
      </div>
    </div>
    <!-- end of contact page  -->
  </div> <!-- end of container -->

server/src/templates/layouts/footer.html
    <!-- firebase -->
     <!-- toastify -->
     <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>

     <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.12.0/toastify.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.12.0/toastify.min.js"></script>
    <!-- end toastify -->
    <script src="/js/lib/sweetalert2.js"></script>
    <script src="/js/lib/pooper.js"></script>
    <script src="/js/lib/bootstrap.min.js"></script>
    <script src="/js/config.js"></script>
  

    <script src="/js/firebase.js" type="module"></script>
    <script src="/js/helper.js"></script>
    <script src="/js/validation.js"></script>
    <!-- <script src="/js/worker.js"></script> -->
    <!-- main js -->
    <script src="/js/user.js" type="module"></script>
    <script src="/js/logout.js" type="module"></script>


    {% if messages %}
    <script>
            const Toast = Swal.mixin({
    customClass: 'swal-upload',
    toast: true,
    position: "top-end",
    showConfirmButton: false,
    timer: 3000,
    color: "#b58126",
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.onmouseenter = Swal.stopTimer;
      toast.onmouseleave = Swal.resumeTimer;
    }
    });
    Toast.fire({
    icon: "{{ messages['type'] }}",
    title: "{{  messages['msg'] }}"
    }); // end of alert
    
    
    var mustLogin = "{{  messages['mustLogin'] }}"
    if(mustLogin === "True")
    {
    document.querySelector(".sign-in").click()
    }
    
    </script>
    {% endif %}

    <script src="/js/tools/calc.js"></script>
    <script src="/js/tools/chatbot.js"></script>
    <script src="/js/tools/target.js"></script>
    <script src="/js/tools/record.js"></script>
    <script src="/js/notification.js"></script>
    <script src="/js/script.js"></script>
    <script src="/js/main.js"></script>

server/src/templates/layouts/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.css" />
    <link href="/css/lib/fontawesome.css" rel="stylesheet">
    <link href="/css/lib/glutin-fonts.css" rel="stylesheet">
    <link
    href="/css/lib/poppins-fonts.css" rel="stylesheet">
    <!-- fonts -->
    <!-- alert -->
    <link href="/css/lib/sweetalert2.css" rel="stylesheet">
    <!-- bootstrap -->
    <link href="/css/lib/bootstrap.css" media="screen" rel="stylesheet">
    <title>{{ pagetitle }}</title>
    <meta name="description"
        content="this site made by dr hasan (dr.null) to help his friends to find solution to bypass restriction from other bad people who block sharing files">
    <meta name="robots" content="index,follow">
    <meta name="googlebot" content="index,follow">
    <meta name="keywords" content="HTML, CSS, JavaScript ,TANTA , egypt,al-dawaa,dawa,pharmacist,pharmacy,design">
    <meta name="author" content="Dr.Null(Hasan Meady)">
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="manifest" href="/js/manifest.json" />
    <!-- ios support -->
    <link rel="apple-touch-icon" href="/images/icon-192x192.png">
    <link rel="apple-touch-icon" href="/images/icon-256x256.png">
    <link rel="apple-touch-icon" href="/images/icon-384x384.png">
    <link rel="apple-touch-icon" href="/images/icon-512x512.png">



    <meta name="apple-mobile-web-app-status-bar" content="#fbfbfb" />
    <meta name="theme-color" content="#fbfbfb" />

    <link href="/css/components.css" rel="stylesheet" type="text/css" />
    <link href="/css/files.css" rel="stylesheet" type="text/css" />
    <link href="/css/tools/chatbot.css" rel="stylesheet" type="text/css" />
    <link href="/css/tools/calc.css" rel="stylesheet" type="text/css" />
    <link href="/css/tools/target.css" rel="stylesheet" type="text/css" />
    <link href="/css/tools/record.css" rel="stylesheet" type="text/css" />
    <link href="/css/nav.css" rel="stylesheet" type="text/css" /> 
    <link href="/css/modal.css" rel="stylesheet" type="text/css" /> 
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="this site made by dr hasan (dr.null) to help his friends to find solution to bypass restriction from other bad people who block sharing files">

    <style>
        .main.spinners {
            display: block;
        }

        .main.overlay {
            display: block;
        }
    </style>
    <!-- <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5814855103569462"
     crossorigin="anonymous"></script> -->

    {% if url_for(request.endpoint)  == '/book': %}
    <script src="/js/lib/jquery.min.1.7.js"></script>
    {% else %}
    <script src="/js/lib/jquery-3.7.1.min.js"></script>
    {% endif %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/11.7.0/math.min.js"></script>

server/src/templates/layouts/nav.html
<nav id="nav">
  <div class="logo">
    <h1 class="heading-1">
      <span class="color-letter">H</span><span>a</span><span>s</span><span>a</span><span>n</span>
    </h1>
  </div>
  <div class="right-links">
    <!-- Links -->
    <div class="right-links">
      <div class="links outer-links">
        {% block nav %}
        {% endblock %}
        {% if isLogged == True %}
        <a href="{{ url_for('library.library_page') }}" class="heading-nav {% if url_for(request.endpoint) == '/library' %}active{% endif %}">Files Library</a>
          <a href="{{ url_for('ydownload.downloadpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/download' %}active{% endif %}">YDownload</a>
          <a href="{{ url_for('upload.upload_page') }}" class="heading-nav {% if url_for(request.endpoint) == '/upload' %}active{% endif %}">Upload Files</a>
          <a href="{{ url_for('search.searchpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/search' %}active{% endif %}">Magic Search</a>
          <a href="{{ url_for('notes.notespage') }}" class="heading-nav {% if url_for(request.endpoint) == '/notes' %}active{% endif %}">Notes</a>
          <a href="{{ url_for('cvmaker.cvmakerpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/cvmaker' %}active{% endif %}">Cv Maker</a>
          <a href="#" class="heading-nav calc" aria-label="calc" data-bs-toggle="modal" data-bs-target="#calcModal">Calc</a>
          <a href="#" class="heading-nav target" aria-label="target" data-bs-toggle="modal" data-bs-target="#targetModal">Target</a>
          <a href="#" class="heading-nav record recording-toggle" title="record screen">Record</a>
          <a href="{{ url_for('dashboard.dashboardpage') }}" class="heading-nav dashboard {% if url_for(request.endpoint) == '/dashboard' %}active{% endif %}">Dashboard</a>
          <a href="#" class="heading-nav logout">Logout</a>
        {% else %}
          <a href="{{ url_for('ydownload.downloadpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/download' %}active{% endif %}">YDownload</a>
          <a href="{{ url_for('search.searchpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/search' %}active{% endif %}">Magic Search</a>
          <a href="{{ url_for('cvmaker.cvmakerpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/cvmaker' %}active{% endif %}">Cv Maker</a>
          <a href="#" class="heading-nav calc" aria-label="calc" data-bs-toggle="modal" data-bs-target="#calcModal">Calc</a>
          <a href="#" class="heading-nav record recording-toggle" title="record screen">Record</a>
          <a href="#" class="heading-nav sign-in" aria-label="login" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
          <a href="#" class="heading-nav register" aria-label="register" data-bs-toggle="modal" data-bs-target="#registerModal">Register</a>
          <a href="{{ url_for('dashboard.dashboardpage') }}" class="heading-nav dashboard {% if url_for(request.endpoint) == '/dashboard' %}active{% endif %}">Dashboard</a>
        {% endif %}
      </div>
    </div>

    <!-- Enable permission icon -->
    <div class="dropdown" data-bs-auto-close="outside">
      <i class="fa-solid fa-sliders notify-perm dropdown-toggle text-muted opacity-50" disabled  title="allow permissions" id="notificationDropdown" data-bs-toggle="dropdown" aria-expanded="false"></i>
      <ul class="dropdown-menu permssion-dropdown" aria-labelledby="notificationDropdown">
        <li class="text-muted">
          <label class="dropdown-item" for="notificationToggle" >
            Enable Notification
            <input type="checkbox" disabled class="form-check-input cutsom-check" id="notificationToggle">
          </label>
        </li>
        <li class="text-muted">
          <label class="dropdown-item" for="locationToggle" >
            Enable Location
            <input type="checkbox" disabled class="form-check-input cutsom-check" id="locationToggle">
          </label>
        </li>
      </ul>
    </div>

    <!-- Menu button -->
    <div class="menu-btn">
      <i class="fa-solid fa-bars burger"></i>
      <div class="links inner-links">
        {% block innerlinks %}
        {% endblock %}
        {% if isLogged == True %}
        <a href="{{ url_for('library.library_page') }}" class="heading-nav {% if url_for(request.endpoint) == '/library' %}active{% endif %}">Files Library</a>
          <a href="{{ url_for('ydownload.downloadpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/download' %}active{% endif %}">YDownload</a>
          <a href="{{ url_for('search.searchpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/search' %}active{% endif %}">Magic Search</a>
          <a href="{{ url_for('upload.upload_page') }}" class="heading-nav {% if url_for(request.endpoint) == '/upload' %}active{% endif %}">Upload Files</a>
          <a href="{{ url_for('notes.notespage') }}" class="heading-nav {% if url_for(request.endpoint) == '/notes' %}active{% endif %}">Notes</a>
          <a href="{{ url_for('cvmaker.cvmakerpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/cvmaker' %}active{% endif %}">Cv Maker</a>
          <a href="#" class="heading-nav calc" aria-label="calc" data-bs-toggle="modal" data-bs-target="#calcModal">Calc</a>
          <a href="#" class="heading-nav target" aria-label="target" data-bs-toggle="modal" data-bs-target="#targetModal">Target</a>
          <a href="#" class="heading-nav record recording-toggle" title="record screen">Record</a>
          <a href="#" class="heading-nav logout">Logout</a>
          <a href="{{ url_for('dashboard.dashboardpage') }}" class="heading-nav dashboard {% if url_for(request.endpoint) == '/dashboard' %}active{% endif %}">Dashboard</a>
        {% else %}
          <a href="{{ url_for('ydownload.downloadpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/download' %}active{% endif %}">YDownload</a>
          <a href="{{ url_for('search.searchpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/search' %}active{% endif %}">Magic Search</a>
          <a href="{{ url_for('cvmaker.cvmakerpage') }}" class="heading-nav {% if url_for(request.endpoint) == '/cvmaker' %}active{% endif %}">Cv Maker</a>
          <a href="#" class="heading-nav calc" aria-label="calc" data-bs-toggle="modal" data-bs-target="#calcModal">Calc</a>
          <a href="#" class="heading-nav record recording-toggle" title="record screen">Record</a>
          <a href="#" class="heading-nav sign-in" aria-label="login" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
          <a href="#" class="heading-nav register" aria-label="register" data-bs-toggle="modal" data-bs-target="#registerModal">Register</a>
          <a href="{{ url_for('dashboard.dashboardpage') }}" class="heading-nav dashboard {% if url_for(request.endpoint) == '/dashboard' %}active{% endif %}">Dashboard</a>
        {% endif %}
      </div>
    </div>

    <i class="fa-solid fa-moon" style="margin-left: 16px;"></i>
  </div>
</nav>

<!-- Notification trigger button -->

server/src/templates/layouts/spinner.html




  <!-- spinners -->
  <div class="main spinners">
    <div class="spinner-grow text-primary" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-success" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-danger" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-warning" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-info" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
  <!-- spinners -->

  <!-- overlay -->
  <div class="main overlay"></div>
  <!-- overlay -->